# Generated by Django 3.1.2 on 2020-12-19 12:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20201219_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[480, 320], upload_to='pictures'),
        ),
    ]
