# Generated by Django 3.1.2 on 2020-12-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
