# Generated by Django 3.1.2 on 2020-12-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20201225_1949'),
        ('test_app', '0007_auto_20201226_1723'),
    ]

    operations = [
    ]
