# Generated by Django 3.1.2 on 2020-12-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_merge_20201228_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
