# Generated by Django 3.1.2 on 2020-12-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_auto_20201229_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
    ]
