# Generated by Django 3.1.2 on 2020-12-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_auto_20201229_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
